version: 2
updates:
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: yearly
    assignees:
      - 178inaba
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: yearly
    assignees:
      - 178inaba
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: yearly
    assignees:
      - 178inaba
